services:
  catalogdb:
    image: postgres:latest
  identitydb:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:







